import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Terms of Use</h1>
        <p className="text-slate-500 mb-8 text-sm">Last updated: January 2025</p>
        <div className="space-y-6 text-slate-700">
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-2">1. Educational Purpose Only</h2>
            <p>The Digital Parenting Score Calculator is provided for educational and informational purposes only. It is not a medical, psychological, or clinical assessment tool. Results should not be used as a substitute for professional advice.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-2">2. No Professional Advice</h2>
            <p>The scores and recommendations generated by this tool are based on general guidelines and publicly available research. They do not constitute professional medical, psychological, or educational advice. Always consult a qualified professional for specific concerns.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-2">3. Free to Use</h2>
            <p>This tool is free to use for personal, non-commercial purposes. You may not reproduce, redistribute, or sell this tool or its outputs for commercial gain.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-2">4. Limitation of Liability</h2>
            <p>We make no warranties about the accuracy or completeness of the information provided. We are not liable for any decisions made based on this tool's outputs.</p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}
